apiVersion: apps/v1
kind: Deployment
metadata:
  name: orbis-python-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orbis-python
  template:
    metadata:
      labels:
        app: orbis-python
    spec:
      containers:
        - name: orbis-python
          image: orbis-python:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
