apiVersion: v1
kind: Service
metadata:
  name: dockerfile-generator
spec:
  selector:
    app: dockerfile-generator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer 