name: Run Jenkins Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  run-jenkins:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Jenkins Pipeline
        run: |
          docker run --rm \
            -u root \
            -v $(pwd):/workspace \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -w /workspace \
            jenkins/jenkins:lts-jdk11 \
            bash -c "apt-get update && \
                    apt-get install -y python3 python3-pip python3-venv && \
                    python3 -m venv /workspace/venv && \
                    . /workspace/venv/bin/activate && \
                    pip install pytest && \
                    java -jar /usr/share/jenkins/jenkins.war -httpPort=8080 & \
                    echo 'Waiting for Jenkins to start...' && \
                    while ! curl -s http://localhost:8080 > /dev/null; do sleep 1; done && \
                    echo 'Jenkins is up!' && \
                    sleep 10 && \
                    curl -X POST http://localhost:8080/job/dockerfile-generator/build \
                    --user admin:$(cat /run/secrets/additional/secrets-store/additional/initialAdminPassword)" 